# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-16 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCourse',
            new_name='UserDrama',
        ),
    ]
